#!/bin/bash
###############################################################################
# Copyright (c) 2005, projektfarm Gmbh, Till Brehm, Falko Timme
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of ISPConfig nor the names of its contributors
#       may be used to endorse or promote products derived from this software without
#       specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###############################################################################

PATH="/home/admispconfig/ispconfig/tools/clamav/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/libexec"

OPENSSL=openssl-0.9.8e
APACHE=apache_1.3.37
MOD_SSL=mod_ssl-2.8.28-1.3.37
PHP=php-5.2.1
CLAMAV=clamav-0.90.2
CLAMASSASSIN=clamassassin-1.2.3a
UUDEVIEW=uudeview-0.5.20
SPAMASSASSIN=Mail-SpamAssassin-3.2.0
CRONOLOG=cronolog-1.6.2
ZIP=zip-2.3
UNZIP=unzip-5.52

APPLICATION_NAME=ispconfig
INSTALL_ROOT=/root/${APPLICATION_NAME}
INSTALL_ROOT_TMP=${INSTALL_ROOT}_tmp
COMPILE_DIR=`pwd`
ARCH=`uname -m`

if [ $ARCH == "x86_64" ]; then
  WITH_OPENSSL="--with-openssl"
  if echo "$dist" | grep -q "fedora" || echo "$dist" | grep -q "suse" || echo "$dist" | grep -q "centos" ; then
    mkdir -p /usr/local/lib/mysql &> /dev/null
    ln -s /usr/include/mysql /usr/local/lib/mysql/include &> /dev/null
    ln -s /usr/lib64/mysql /usr/local/lib/mysql/lib &> /dev/null

    WITH_MYSQL="--with-mysql=/usr/local/lib/mysql"
    WITH_ZLIB_DIR="--with-zlib-dir=/usr/lib64"
  elif echo "$dist" | grep -q "mdk" || echo "$dist" | grep -q "mdr" ; then
    mkdir -p /usr/local/lib/mysql &> /dev/null
    ln -s /usr/include/mysql /usr/local/lib/mysql/include &> /dev/null
    ln -s /usr/lib64 /usr/local/lib/mysql/lib &> /dev/null

    WITH_MYSQL="--with-mysql=/usr/local/lib/mysql"
    WITH_ZLIB_DIR="--with-zlib-dir=/usr/lib64"
  else
    WITH_MYSQL="--with-mysql=/usr"
    WITH_ZLIB_DIR=""
  fi
else
  WITH_OPENSSL="--with-openssl=${INSTALL_ROOT}/openssl"
  WITH_MYSQL="--with-mysql=/usr"
  WITH_ZLIB_DIR=""
fi

error ()
{
  echo "ERROR: $1"
  if [ -d ${INSTALL_ROOT} ]
  then
    rm -fr ${INSTALL_ROOT}
  fi
  if [ -d ${INSTALL_ROOT_TMP} ]
  then
    rm -fr ${INSTALL_ROOT_TMP}
  fi
  cd ${COMPILE_DIR}
  rm -fr ${OPENSSL}
  rm -fr ${APACHE}
  rm -fr ${MOD_SSL}
  rm -fr ${PHP}
  rm -fr ${CLAMAV}
  rm -fr ${CLAMASSASSIN}
  rm -fr ${SPAMASSASSIN}
  rm -fr ${UUDEVIEW}
  rm -fr ${CRONOLOG}
  rm -fr ${ZIP}
  rm -fr ${UNZIP}
  exit 1
}

tar xvfz ${OPENSSL}.tar.gz || error "Could not unpack OpenSSL"
tar xvfz ${APACHE}.tar.gz || error "Could not unpack Apache"
tar xvfz ${MOD_SSL}.tar.gz || error "Could not unpack mod_ssl"
tar xvfz ${PHP}.tar.gz || error "Could not unpack PHP"
tar xvfz ${CLAMAV}.tar.gz || error "Could not unpack ClamAV"
tar xvfz ${CLAMASSASSIN}.tar.gz || error "Could not unpack ClamAssassin"
tar xvfz ${SPAMASSASSIN}.tar.gz || error "Could not unpack SpamAssassin"
tar xvfz ${UUDEVIEW}.tar.gz || error "Could not unpack uudeview"
tar xvfz ${CRONOLOG}.tar.gz || error "Could not unpack cronolog"
tar xvfz ${ZIP}.tar.gz || error "Could not unpack zip"
tar xvfz ${UNZIP}.tar.gz || error "Could not unpack unzip"

cd ${OPENSSL}
./config --prefix=${INSTALL_ROOT}/openssl || error "Could not configure OpenSSL"
make || error "Could not make OpenSSL"
make install || error "Could not install OpenSSL"

cd ../${MOD_SSL}
./configure --with-apache=../${APACHE} --with-ssl=${INSTALL_ROOT}/openssl --prefix=${INSTALL_ROOT}/httpd --enable-module=so || error "Could not configure Apache"
cd ../${APACHE}
make || error "Could not make Apache"
make certificate TYPE=custom  || error "Could not make certificate for Apache"
make install || error "Could not install Apache"

cd ../${PHP}
./configure --with-apxs=${INSTALL_ROOT}/httpd/bin/apxs --enable-track-vars --enable-sockets --enable-mbstring=all --with-config-file-path=${INSTALL_ROOT}/php --enable-ftp --prefix=${INSTALL_ROOT}/php ${WITH_OPENSSL} ${WITH_MYSQL} --disable-libxml --disable-dom --disable-xml ${WITH_ZLIB_DIR} --disable-xmlreader --disable-xmlwriter --disable-simplexml --without-pear || error "Could not configure PHP"
make || error "Could not make PHP"
make install || error "Could not install PHP"
ln -s ${INSTALL_ROOT}/php/bin/php ${INSTALL_ROOT}/php/php

cd ${COMPILE_DIR}
cp -pf php.ini ${INSTALL_ROOT}/php/php.ini
chmod 644 ${INSTALL_ROOT}/php/php.ini
chown root:root ${INSTALL_ROOT}/php/php.ini

rm -f ${INSTALL_ROOT}/httpd/conf/httpd.conf
cp -pf httpd.conf_http ${INSTALL_ROOT}/httpd/conf/httpd.conf_http
chmod 644 ${INSTALL_ROOT}/httpd/conf/httpd.conf_http
chown root:root ${INSTALL_ROOT}/httpd/conf/httpd.conf_http

cp -pf httpd.conf_https ${INSTALL_ROOT}/httpd/conf/httpd.conf_https
chmod 644 ${INSTALL_ROOT}/httpd/conf/httpd.conf_https
chown root:root ${INSTALL_ROOT}/httpd/conf/httpd.conf_https

mv -f ${INSTALL_ROOT}/httpd/bin/httpd ${INSTALL_ROOT}/httpd/bin/${APPLICATION_NAME}_httpd
cp -f apachectl ${INSTALL_ROOT}/httpd/bin/apachectl
chmod 755 ${INSTALL_ROOT}/httpd/bin/apachectl
chown root:root ${INSTALL_ROOT}/httpd/bin/apachectl

mv -f ${INSTALL_ROOT} ${INSTALL_ROOT_TMP}
cd /root
tar -pczf ${COMPILE_DIR}/../binaries/aps.tar.gz ${APPLICATION_NAME}_tmp || error "Could not create aps.tar.gz"
rm -fr ${INSTALL_ROOT_TMP}
cd ${COMPILE_DIR}

cd ${CLAMAV}
./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --sysconfdir=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc --with-user=adm${APPLICATION_NAME} --with-group=adm${APPLICATION_NAME} --disable-clamav --disable-bzip2 --disable-zlib-vcheck || error "Could not configure ClamAV"
make || error "Could not make ClamAV"
make install || error "Could not install ClamAV"
cp -f COPYING /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/
cd ${COMPILE_DIR}
cp -f clamav.conf /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/clamav.conf
cp -f freshclam.conf /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/freshclam.conf
rm -f /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/clamd.conf
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/
ln -s clamav.conf clamd.conf
cd ${COMPILE_DIR}
cd ${CLAMASSASSIN}

grep -w ^adm${APPLICATION_NAME} /etc/group &> /dev/null
if [ $? != 0 ]; then
  groupadd adm${APPLICATION_NAME} &> /dev/null
  DELGROUP=1
else
  DELGROUP=0
fi
grep -w ^adm${APPLICATION_NAME} /etc/passwd &> /dev/null
if [ $? != 0 ]; then
  useradd adm${APPLICATION_NAME} -g adm${APPLICATION_NAME} &> /dev/null
  DELUSER=1
else
  DELUSER=0
fi
mkdir -p /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/share/clamav
chown -R adm${APPLICATION_NAME}:adm${APPLICATION_NAME} /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/share
./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --disable-clamdscan
make install
if [ "$DELUSER" -eq "1" ]; then
  userdel adm${APPLICATION_NAME} &> /dev/null
fi
if [ "$DELGROUP" -eq "1" ]; then
  groupdel adm${APPLICATION_NAME} &> /dev/null
fi

cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/
tar -pczf ${COMPILE_DIR}/../binaries/clamav.tar.gz clamav/ || error "Could not create clamav.tar.gz"
cd ${COMPILE_DIR}

cd ${SPAMASSASSIN}
perl Makefile.PL PREFIX=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/spamassassin/usr SYSCONFDIR=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/spamassassin/etc || error "Could not configure SpamAssassin"
make || error "Could not make SpamAssassin"
make install || error "Could not install SpamAssassin"
cp -f LICENSE /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/spamassassin/
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools
tar -pczf ${COMPILE_DIR}/../binaries/spamassassin.tar.gz spamassassin/ || error "Could not create spamassassin.tar.gz"
cd ${COMPILE_DIR}

cd ${UUDEVIEW}
./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/uudeview || error "Could not configure UUDeview"
make || error "Could not make UUDeview"
make install || error "Could not install UUDeview"
cp -f COPYING /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/uudeview/
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools
tar -pczf ${COMPILE_DIR}/../binaries/uudeview.tar.gz uudeview/ || error "Could not create uudeview.tar.gz"
cd ${COMPILE_DIR}

cd ${CRONOLOG}
./configure || error "Could not configure cronolog"
make || error "Could not make cronolog"
mv src/cronolog ${COMPILE_DIR}/../binaries/cronolog || error "Could not copy cronolog"
mv src/cronosplit ${COMPILE_DIR}/../binaries/cronosplit || error "Could not copy cronosplit"
cd ${COMPILE_DIR}

cd ${ZIP}
make -f unix/Makefile generic || error "Could not make zip"
mv zip ${COMPILE_DIR}/../binaries/zip || error "Could not copy zip"
cd ${COMPILE_DIR}

cd ${UNZIP}
make -f unix/Makefile generic || error "Could not make unzip"
mv unzip ${COMPILE_DIR}/../binaries/unzip || error "Could not copy unzip"
cd ${COMPILE_DIR}

exit 0