#!/bin/bash
###############################################################################
# Copyright (c) 2005, projektfarm Gmbh, Till Brehm, Falko Timme
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of ISPConfig nor the names of its contributors
#       may be used to endorse or promote products derived from this software without
#       specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###############################################################################

PATH="/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/libexec"

OPENSSL=openssl-0.9.8
APACHE=apache_1.3.33
MOD_SSL=mod_ssl-2.8.23-1.3.33
PHP=php-5.0.4
CLAMAV=clamav-0.87
UUDEVIEW=uudeview-0.5.20

APPLICATION_NAME=ispconfig
INSTALL_ROOT=/root/${APPLICATION_NAME}
INSTALL_ROOT_TMP=${INSTALL_ROOT}_tmp
COMPILE_DIR=`pwd`

error ()
{
  echo "ERROR: $1"
  if [ -d ${INSTALL_ROOT} ]
  then
    rm -fr ${INSTALL_ROOT}
  fi
  if [ -d ${INSTALL_ROOT_TMP} ]
  then
    rm -fr ${INSTALL_ROOT_TMP}
  fi
  cd ${COMPILE_DIR}
  rm -fr ${OPENSSL}
  rm -fr ${APACHE}
  rm -fr ${MOD_SSL}
  rm -fr ${PHP}
  rm -fr ${CLAMAV}
  rm -fr ${UUDEVIEW}
  exit 1
}

tar xvfz ${OPENSSL}.tar.gz || error "Could not unpack OpenSSL"
tar xvfz ${APACHE}.tar.gz || error "Could not unpack Apache"
tar xvfz ${MOD_SSL}.tar.gz || error "Could not unpack mod_ssl"
tar xvfz ${PHP}.tar.gz || error "Could not unpack PHP"
tar xvfz ${CLAMAV}.tar.gz || error "Could not unpack ClamAV"
tar xvfz ${UUDEVIEW}.tar.gz || error "Could not unpack uudeview"

cd ${OPENSSL}
./config --prefix=${INSTALL_ROOT}/openssl || error "Could not configure OpenSSL"
make || error "Could not make OpenSSL"
make install || error "Could not install OpenSSL"

cd ../${MOD_SSL}
./configure --with-apache=../${APACHE} --with-ssl=${INSTALL_ROOT}/openssl --prefix=${INSTALL_ROOT}/httpd --enable-module=so || error "Could not configure Apache"
cd ../${APACHE}
make || error "Could not make Apache"
make certificate TYPE=custom  || error "Could not make certificate for Apache"
make install || error "Could not install Apache"

cd ../${PHP}
./configure --with-apxs=${INSTALL_ROOT}/httpd/bin/apxs --enable-track-vars --enable-sockets --enable-mbstring=all --with-config-file-path=${INSTALL_ROOT}/php --enable-ftp --prefix=${INSTALL_ROOT}/php --with-openssl=${INSTALL_ROOT}/openssl --with-mysql=/usr --with-pgsql=/usr --disable-libxml || error "Could not configure PHP"
make || error "Could not make PHP"
make install || error "Could not install PHP"
ln -s ${INSTALL_ROOT}/php/bin/php ${INSTALL_ROOT}/php/php

cd ${COMPILE_DIR}
cp -pf php.ini ${INSTALL_ROOT}/php/php.ini
chmod 644 ${INSTALL_ROOT}/php/php.ini
chown root:root ${INSTALL_ROOT}/php/php.ini

rm -f ${INSTALL_ROOT}/httpd/conf/httpd.conf
cp -pf httpd.conf_http ${INSTALL_ROOT}/httpd/conf/httpd.conf_http
chmod 644 ${INSTALL_ROOT}/httpd/conf/httpd.conf_http
chown root:root ${INSTALL_ROOT}/httpd/conf/httpd.conf_http

cp -pf httpd.conf_https ${INSTALL_ROOT}/httpd/conf/httpd.conf_https
chmod 644 ${INSTALL_ROOT}/httpd/conf/httpd.conf_https
chown root:root ${INSTALL_ROOT}/httpd/conf/httpd.conf_https

mv -f ${INSTALL_ROOT}/httpd/bin/httpd ${INSTALL_ROOT}/httpd/bin/${APPLICATION_NAME}_httpd
cp -f apachectl ${INSTALL_ROOT}/httpd/bin/apachectl
chmod 755 ${INSTALL_ROOT}/httpd/bin/apachectl
chown root:root ${INSTALL_ROOT}/httpd/bin/apachectl

mv -f ${INSTALL_ROOT} ${INSTALL_ROOT_TMP}
cd /root
tar -pczf ${COMPILE_DIR}/../binaries/aps.tar.gz ${APPLICATION_NAME}_tmp || error "Could not create aps.tar.gz"
rm -fr ${INSTALL_ROOT_TMP}
cd ${COMPILE_DIR}

cd ${CLAMAV}
./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --sysconfdir=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc --with-user=adm${APPLICATION_NAME} --with-group=adm${APPLICATION_NAME} --disable-clamav --disable-bzip2 || error "Could not configure ClamAV"
make || error "Could not make ClamAV"
make install || error "Could not install ClamAV"
cp -f COPYING /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/
cd ${COMPILE_DIR}
cp -f clamav.conf /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/clamav.conf
cp -f freshclam.conf /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/freshclam.conf
rm -f /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/clamd.conf
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc/
ln -s clamav.conf clamd.conf
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/
tar -pczf ${COMPILE_DIR}/../binaries/clamav.tar.gz clamav/ || error "Could not create clamav.tar.gz"
cd ${COMPILE_DIR}

cd ${UUDEVIEW}
./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/uudeview || error "Could not configure UUDeview"
make || error "Could not make UUDeview"
make install || error "Could not install UUDeview"
cp -f COPYING /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/uudeview/
cd /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools
tar -pczf ${COMPILE_DIR}/../binaries/uudeview.tar.gz uudeview/ || error "Could not create uudeview.tar.gz"
cd ${COMPILE_DIR}

exit 0