#!/bin/bash
###############################################################################
# Copyright (c) 2005, projektfarm Gmbh, Till Brehm, Falko Timme
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of ISPConfig nor the names of its contributors
#       may be used to endorse or promote products derived from this software without
#       specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###############################################################################

###################################
#
# ISPConfig tcpserver-Startscript
#
###################################

prog_name="ispconfig_tcpserver"
prog=/home/admispconfig/ispconfig/tools/tcpserver/ispconfig_tcpserver
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/X11R6/bin

RETVAL=0

start(){
    echo -n $"Starting $prog_name"
    which ip &> /dev/null
    if [ $? != 0 ]; then
      OS=`uname -s`
      if [ "$OS" == "FreeBSD" ]; then
        array=(`ifconfig | grep -iw 'inet' | grep -iv 'inet6' | cut -f2 -d' ' | tr '\n' ' '`)
      else
        array=(`ifconfig | grep -iw 'inet' | cut -f2 -d: | cut -f1 -d' ' | tr '\n' ' '`)
      fi
    else
      array=(`ip addr show | grep -iw 'inet' | awk '{print $2}' | cut -f1 -d/ | tr '\n' ' '`)
    fi
    element_count=${#array[@]}
    index=0
    while [ "$index" -lt "$element_count" ]
    do
      if [ -f /etc/vsftpd_${array[$index]}.conf ] && [ "${array[$index]}" != "" ];
      then
        $prog ${array[$index]} ftp `which vsftpd` /etc/vsftpd_${array[$index]}.conf &
      fi
      let "index = $index + 1"
    done
    RETVAL=$?
    echo
    return $RETVAL
}

stop(){
    echo -n $"Stopping $prog_name "
    array=(`ps ax | grep -iw "$prog" | grep -iv 'grep' | awk '{print $1}' | cut -f1 -d/ | tr '\n' ' '`)
    element_count=${#array[@]}
    index=0
    while [ "$index" -lt "$element_count" ]
    do
      kill -15 ${array[$index]}
      let "index = $index + 1"
    done

    RETVAL=$?
    echo
    return $RETVAL

}

restart(){
    stop
    start
}


# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        RETVAL=1
esac

exit $RETVAL