		<p align="center"><font color="#FFFFFF"><font size="2" face="Verdana"><b>Legende:</b></font>&nbsp; <img border="0" src="bilder/vzzu-0.gif" width="16" height="16"> <font size="2" face="Verdana">Ordner&nbsp;
      <img border="0" src="bilder/ini.gif" width="16" height="16"> Eintrag
      bearbeiten&nbsp; <img border="0" src="bilder/globus.gif" width="16" height="16">
      Link&nbsp; <img border="0" src="bilder/email.gif" width="16" height="16">
      Email&nbsp; <img border="0" src="bilder/adresse.gif" width="16" height="16">
      Adresse</font></font></p>